import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { NavBar } from "./_components/navbar";

const poppins = Poppins({ subsets: ["latin-ext"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark antialiased`}>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          <main className="flex h-screen w-screen flex-row overflow-x-hidden">
            <NavBar />
            <div className="h-full w-full">{children}</div>
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}
